# Generated by Django 6.0.2 on 2026-06-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_alter_branch_closing_time_alter_branch_opening_time'),
        ('queues', '0023_alter_token_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., NH-44, Yamuna Expressway', max_length=100, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HighwayBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_km', models.DecimalField(decimal_places=2, help_text='KM marker along the highway', max_digits=6)),
                ('direction_of_travel', models.CharField(choices=[('UP', 'Towards End Point'), ('DOWN', 'Towards Start Point'), ('BOTH', 'Accessible from both sides')], default='BOTH', max_length=20)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('exclusivity_range_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Exclusivity range in km', max_digits=5)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highway_info', to='organization.branch')),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.highway')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='organization.branch')),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Near India Gate, Sector 62', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='organization.branch')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=30)),
                ('order_type', models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway')], default='dine_in', max_length=20)),
                ('estimated_prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='organization.branch')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_order', to='queues.token')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurantorder')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='organization.branch')),
            ],
            options={
                'unique_together': {('branch', 'table_number')},
            },
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.table'),
        ),
    ]
