# Generated by Django 6.0.2 on 2026-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes'),
        ),
    ]
