# Generated by Django 6.0.2 on 2026-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_menuitem_preparation_time_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='preparing', max_length=30),
        ),
    ]
