# Generated by Django 6.0.2 on 2026-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurantorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='expected_arrival_time',
            field=models.TimeField(blank=True, help_text="Customer's expected arrival time at the restaurant", null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('tentative', 'Tentative Confirmation'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=30),
        ),
    ]
