# Generated by Django 6.0.2 on 2026-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_add_expected_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantorder',
            name='expected_arrival_time',
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='minutes_until_arrival',
            field=models.PositiveIntegerField(blank=True, help_text='How many minutes until customer arrives at the restaurant', null=True),
        ),
    ]
