# Generated by Django 6.0.2 on 2026-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_minutes_until_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='customer_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
