# Generated by Django 6.0.2 on 2026-06-07 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantorder_customer_arrived'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighwaySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(help_text='e.g. Delhi', max_length=100)),
                ('end_place', models.CharField(help_text='e.g. Agra', max_length=100)),
                ('start_km', models.DecimalField(decimal_places=2, help_text='Start KM milestone along the highway', max_digits=6)),
                ('end_km', models.DecimalField(decimal_places=2, help_text='End KM milestone along the highway', max_digits=6)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='restaurants.highway')),
            ],
            options={
                'verbose_name': 'Highway Segment',
                'verbose_name_plural': 'Highway Segments',
                'unique_together': {('highway', 'start_place', 'end_place')},
            },
        ),
    ]
