# Generated by Django 6.0.2 on 2026-06-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_highwaysegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='highwaybranch',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='The segment/stretch of highway this branch is located in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='restaurants.highwaysegment'),
        ),
    ]
