# Generated by Django 6.0.2 on 2026-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_highwaybranch_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address for Deliver at Home orders', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway'), ('delivery', 'Deliver at Home')], default='dine_in', max_length=20),
        ),
    ]
