# Generated by Django 6.0.2 on 2026-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='expected_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Expected delivery time for home delivery orders', null=True),
        ),
    ]
