# Generated by Django 6.0.2 on 2026-06-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantorder_expected_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Menu Category Name',
                'verbose_name_plural': 'Menu Category Names',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.menucategoryname'),
        ),
    ]
