# Generated by Django 6.0.2 on 2026-06-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_menucategoryname_alter_menucategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_veg', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Global Menu Item',
                'verbose_name_plural': 'Global Menu Items',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_items', to='restaurants.globalmenuitem'),
        ),
    ]
