# Generated by Django 6.0.2 on 2026-05-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
