# Generated by Django 6.0.2 on 2026-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_branch_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='recommended to be filled accurately so that user can know when the branch closes while booking for service', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='recommended to be filled accurately so that user can know when the branch opens while booking for service', null=True),
        ),
    ]
