# Generated by Django 6.0.2 on 2026-05-07 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_branch_closing_time_branch_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 0), help_text='Format: 9:00 PM', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), help_text='Format: 8:00 AM', null=True),
        ),
    ]
