# Generated by Django 6.0.2 on 2026-06-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_branch_closing_time_alter_branch_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='offers_delivery',
            field=models.BooleanField(default=False, help_text='Check if this branch offers home delivery'),
        ),
    ]
