# Generated by Django 6.0.2 on 2026-03-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_branch', to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_organization', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('org_admin', 'Org_Admin'), ('branch_admin', 'Brach_Admin'), ('staff', 'Staff'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('service_provider', 'Service Provider'), ('other', 'Other')], default='customer', max_length=30),
        ),
    ]
