# Generated by Django 6.0.2 on 2026-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_branch_alter_userprofile_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('org_admin', 'org_admin'), ('branch_admin', 'brach_admin'), ('staff', 'staff'), ('supplier', 'supplier'), ('customer', 'customer'), ('service_provider', 'service_provider'), ('other', 'other')], default='customer', max_length=30),
        ),
    ]
