# Generated by Django 6.0.2 on 2026-05-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
