# Generated by Django 6.0.2 on 2026-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='current_serving_number',
            field=models.IntegerField(default=0),
        ),
    ]
