# Generated by Django 6.0.2 on 2026-03-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('queues', '0002_queue_current_serving_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='organization.service'),
        ),
    ]
