# Generated by Django 6.0.2 on 2026-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
    ]
