# Generated by Django 6.0.2 on 2026-03-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_alter_queue_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
