# Generated by Django 6.0.2 on 2026-03-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('queues', '0006_token_end_time_token_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
        migrations.AddField(
            model_name='tokenservice',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
    ]
