# Generated by Django 6.0.2 on 2026-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_token_branch_tokenservice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expected_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='expected_waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
