# Generated by Django 6.0.2 on 2026-03-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('queues', '0008_token_expected_service_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='token',
            name='expected_wait_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expected_service_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='token',
            name='expected_waiting_time',
        ),
        migrations.RemoveField(
            model_name='token',
            name='number',
        ),
        migrations.RemoveField(
            model_name='token',
            name='queue',
        ),
    ]
