# Generated by Django 6.0.2 on 2026-03-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('queues', '0009_alter_token_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expected_wait_minutes',
        ),
        migrations.AddField(
            model_name='token',
            name='expected_waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expected_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.IntegerField(default=0),
        ),
    ]
