# Generated by Django 6.0.2 on 2026-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_remove_token_expected_wait_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='actual_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='expected_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
