# Generated by Django 6.0.2 on 2026-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_token_actual_service_time_token_expected_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
