# Generated by Django 6.0.2 on 2026-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0012_alter_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
