# Generated by Django 6.0.2 on 2026-04-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0013_token_is_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='promos/')),
                ('link', models.URLField(help_text='Where should the button lead?')),
                ('slot', models.CharField(choices=[('popup', 'Login Pop-up'), ('hero', 'Main Dashboard Banner'), ('sidebar', 'Sidebar Tile')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
