# Generated by Django 6.0.2 on 2026-04-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0014_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
