# Generated by Django 6.0.2 on 2026-05-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0016_cart_guest_token_guest_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
