# Generated by Django 6.0.2 on 2026-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0017_token_token_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
