# Generated by Django 6.0.2 on 2026-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0020_token_cashback_amount_token_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
