# Generated by Django 6.0.2 on 2026-05-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0021_token_booking_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pay_at_salon', 'Pay at Salon'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='token',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
