# Generated by Django 6.0.2 on 2026-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0022_token_payment_status_token_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pay_at_shop', 'Pay at Shop'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
