# Generated by Django 6.0.2 on 2026-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0023_alter_token_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pay_at_shop', 'Pay at Shop'), ('pay_at_home', 'Pay at Home'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
