# Generated by Django 6.0.2 on 2026-05-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage to apply to the cart total (e.g., 10.00 for 10%)', max_digits=5)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Cashback amount to reward after service completion', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='accounts.promotion')),
            ],
        ),
    ]
