# Generated by Django 6.0.2 on 2026-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promotiondiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Booking Fee', max_length=100)),
                ('fee_logged_in', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for registered / logged-in users', max_digits=10)),
                ('fee_guest', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for guest checkouts', max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional date from which the fee starts applying', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional date after which the fee stops applying', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable or disable this fee setup')),
            ],
        ),
    ]
